getDocs:
  handler: mancomm-handler.getDocs
  events:
    - http:
        path: /v1/docs
        method: get
        cors: true

getTitles:
  handler: mancomm-handler.getTitles
  timeout: 29
  vpc:
    securityGroupIds:
      - sg-05d87901ab73aadcd
    subnetIds:
      - subnet-031b7c29933630637
      - subnet-0800c3b7ada3484f8
      - subnet-05a88013af6fa1872
      - subnet-059a80def7d2afbd9
      - subnet-0cd15f43cc0ab8157
      - subnet-09bfc943b3168ff09
  events:
    - http:
        path: /v1/titles
        method: get
        cors: true

getTitle:
  handler: mancomm-handler.getTitle
  timeout: 29
  vpc:
    securityGroupIds:
      - sg-05d87901ab73aadcd
    subnetIds:
      - subnet-031b7c29933630637
      - subnet-0800c3b7ada3484f8
      - subnet-05a88013af6fa1872
      - subnet-059a80def7d2afbd9
      - subnet-0cd15f43cc0ab8157
      - subnet-09bfc943b3168ff09
  events:
    - http:
        path: /v1/title/{id}
        method: get
        cors: true

saveTitle:
  handler: mancomm-handler.saveTitle
  timeout: 29
  vpc:
    securityGroupIds:
      - sg-05d87901ab73aadcd
    subnetIds:
      - subnet-031b7c29933630637
      - subnet-0800c3b7ada3484f8
      - subnet-05a88013af6fa1872
      - subnet-059a80def7d2afbd9
      - subnet-0cd15f43cc0ab8157
      - subnet-09bfc943b3168ff09
  events:
    - http:
        path: /v1/title
        method: post
        cors: true

deleteTitle:
  handler: mancomm-handler.deleteTitle
  timeout: 29
  vpc:
    securityGroupIds:
      - sg-05d87901ab73aadcd
    subnetIds:
      - subnet-031b7c29933630637
      - subnet-0800c3b7ada3484f8
      - subnet-05a88013af6fa1872
      - subnet-059a80def7d2afbd9
      - subnet-0cd15f43cc0ab8157
      - subnet-09bfc943b3168ff09
  events:
    - http:
        path: /v1/title/{id}
        method: delete
        cors: true

downloadTitle:
  handler: mancomm-handler.downloadTitle
  timeout: 29
  vpc:
    securityGroupIds:
      - sg-05d87901ab73aadcd
    subnetIds:
      - subnet-031b7c29933630637
      - subnet-0800c3b7ada3484f8
      - subnet-05a88013af6fa1872
      - subnet-059a80def7d2afbd9
      - subnet-0cd15f43cc0ab8157
      - subnet-09bfc943b3168ff09
  events:
    - http:
        path: /v1/download/title/{id}
        method: get
        cors: true

processTitle:
  handler: mancomm-handler.processTitle
  timeout: 900
  memorySize: 2048
  vpc:
    securityGroupIds:
      - sg-05d87901ab73aadcd
    subnetIds:
      - subnet-031b7c29933630637
      - subnet-0800c3b7ada3484f8
      - subnet-05a88013af6fa1872
      - subnet-059a80def7d2afbd9
      - subnet-0cd15f43cc0ab8157
      - subnet-09bfc943b3168ff09
  events:
    - s3:
        bucket: mancomm-us-east-1-watch
        event: s3:ObjectCreated:*
        existing: true
        forceDeploy: true

processDBStream:
  handler: mancomm-handler.processDBStream
  timeout: 300
  vpc:
    securityGroupIds:
      - sg-05d87901ab73aadcd
    subnetIds:
      - subnet-031b7c29933630637
      - subnet-0800c3b7ada3484f8
      - subnet-05a88013af6fa1872
      - subnet-059a80def7d2afbd9
      - subnet-0cd15f43cc0ab8157
      - subnet-09bfc943b3168ff09

downloadEvent:
  handler: mancomm-handler.downloadEvent
  timeout: 900
  description: Title download event from SQS
  events:
    - sqs: arn:aws:sqs:us-east-1:381492003455:mancomm-download.fifo